.PHONY: head

head:
    # HTTP/2 200
    # accept-ranges: bytes
    # cache-control: public,max-age=86400
    # content-length: 131903498
    # content-type: application/zip
    # etag: "1ba9b9"
    # last-modified: Fri, 16 Feb 2018 20:10:52 GMT
    # server: downloads
    # x-content-type-options: nosniff
    # x-frame-options: SAMEORIGIN
    # x-xss-protection: 1; mode=block
    # date: Fri, 14 Jun 2019 15:11:38 GMT
    # alt-svc: quic=":443"; ma=2592000; v="46,44,43,39"
	curl -I https://dl.google.com/go/go1.10.windows-amd64.zip
